
version: "3.9"

services:
  database:  #ESSE É O que deve estar no host do ormconfig.json
    image: postgres
    container_name: database_ignite
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: rentx
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local


    ## A utilização do depends_on: => a gente removeu o "network_mode" pq na atualização esse comando deixou de ser compativel com a váriavel ports. A propriedade depends_on irá informar que nosso serviço de api irá depender do serviço do banco de dados (database). Isso fará com que a ordem para os containers subirem seja primeiro o serviço database e depois o da api.

    ## A utilização do links: => A propriedade links faz uma ligação entre os containers,  permitindo que o container de destino (api) tenha informações do container de origem(database). Dessa forma, nosso service da aplicação agora conseguirá se comunicar com nosso banco de dados não mais através do IP, mas sim pelo nome do container. 
